### Numpy

In [45]:
import numpy as np

In [46]:
arr=np.array([1,2,3,4,6])
arr

array([1, 2, 3, 4, 6])

In [47]:
list_of_lists=np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [49]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [56]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [57]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [58]:
np.random.rand(2,5)

array([[0.37965981, 0.5461443 , 0.50455109, 0.18872145, 0.39632491],
       [0.23638254, 0.28295842, 0.32321398, 0.3993133 , 0.93035921]])

In [59]:
np.random.randn(2,5)

array([[ 0.58065695,  0.92654367,  1.66790784,  0.56916628,  0.49122004],
       [-1.18206905, -0.51283074, -0.9519517 ,  0.80406277,  0.0764302 ]])

In [60]:
np.random.randint(1,10)

3

In [61]:
np.random.randint(1,10,100)

array([7, 9, 3, 2, 8, 3, 1, 2, 5, 5, 9, 1, 1, 5, 3, 4, 2, 1, 8, 3, 2, 4,
       9, 5, 7, 7, 5, 5, 4, 8, 1, 1, 8, 9, 3, 6, 6, 1, 5, 4, 7, 6, 2, 8,
       7, 8, 6, 4, 7, 8, 6, 3, 8, 3, 2, 5, 2, 9, 3, 6, 5, 5, 2, 5, 6, 7,
       6, 9, 2, 3, 7, 9, 6, 6, 5, 6, 9, 5, 4, 2, 8, 6, 1, 1, 9, 3, 2, 9,
       1, 6, 5, 5, 8, 1, 4, 7, 9, 5, 1, 7])

In [62]:
np.random.randint(10,1)

ValueError: low >= high

In [ ]:
sample_array=np.arange(30)
sample_array

In [ ]:
sample_array.reshape(5,6)

In [ ]:
sample_array.reshape(5,4)

In [ ]:
rand_array=np.random.randint(0,100,20)
rand_array

In [ ]:
rand_array.min()

In [ ]:
rand_array.max()

In [ ]:
rand_array.argmin()

In [ ]:
rand_array.argmax()

In [ ]:
a=np.random.rand(2,3)
a

In [ ]:
a.T

In [ ]:
sample_array=np.arange(10,21)
sample_array

In [ ]:
sample_array[0]

In [ ]:
sample_array[2:5]

In [ ]:
sample_matrix=np.array(([1,56,34],[34,54,87],[67,90,100]))

In [ ]:
sample_matrix

In [ ]:
sample_matrix[2][2]

In [ ]:
sample_matrix[2]

In [ ]:
sample_matrix[1,:]

In [ ]:
sample_matrix[0,0:2]

In [ ]:
sample_array=np.arange(1,10)

In [ ]:
sample_array

In [ ]:
sample_array+sample_array

In [ ]:
np.log(sample_array)

In [ ]:
np.min(sample_array)

In [ ]:
np.max(sample_array)

In [ ]:
np.sqrt(sample_array)

In [ ]:
np.argmin(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.exp(sample_array)

In [ ]:
np.average(sample_array)

In [ ]:
np.argmin(sample_array)

In [ ]:
np.var(sample_array)

In [ ]:
np.mean(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.std(sample_array)

In [ ]:
array=np.random.randn(3,6)
array

In [ ]:
np.round(array,decimals=3)

In [ ]:
sports=np.array(['golf','cricket','football','golf','basketball','Golf','Golf'])
np.unique(sports)

### Pandas

In [ ]:
import pandas as pd

In [ ]:
labels=['w','x','y','z']
sample_list=[1,2,3,4]
array=np.array([10,11,12,13])
dict={'a':1,'b':2,'y':3,'z':4}

In [ ]:
pd.Series(data=array)

In [ ]:
pd.Series(data=sample_list,index=labels)

In [ ]:
pd.Series(array,labels)

In [ ]:
pd.Series(dict)

In [ ]:
sports1=pd.Series([1,2,3,4],index=["Cricket","Fball","Golf","Basketball"])
sports1

In [ ]:
sports2=pd.Series([11,21,5,6],index=["Cricket","Baseball","Golf","basketball"])
sports2

In [ ]:
sports1+sports2

In [ ]:
df=pd.DataFrame(np.random.rand(6,5),index='A B C D E F'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())

In [ ]:
df

In [ ]:
df={'Id':[100,101,102,103],'Name':['a','b','c','d'],'Marks':[87,23,67,19]}
df1=pd.DataFrame(df)
df1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/edForce/main/CardioGoodFitness-1.csv")

In [ ]:
df

In [ ]:
df.head()

In [ ]:
df.head(10)

In [ ]:
df.sample()

In [ ]:
df.shape

In [ ]:
df.shape[1]

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.describe()

In [ ]:
df.describe(include="all")